server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/my_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进EurekaServer默认为true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群节点必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示ip地址


logging:
  level:
    com.zbl.springcloud.dao: debug