server:
  port: 80

eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进EurekaServer默认为true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群节点必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

spring:
  application:
    name: cloud-order-feign-hystrix-service

feign:
  client:
    config:
      # 这个代表服务，default为任意服务，可以指定服务名来配置调用该服务的超时时间
      default:
        # 建立连接的时间
        connectTimeout: 1000
        # 请求的超时时间
        readTimeout: 5000
  hystrix:
    enabled: true

logging:
  level:
    com.zbl.springcloud.service.PaymentFeignClient: debug
